defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs
  output_subdir: ./configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: log_${now:%Y-%m-%d}_${now:%H-%M-%S}

# datasets
dataset:
  root: '/home/jakhremchik/Documents/code/TMK/Action-Recognition-CNN-LSTM/data/tmk_def_3'
  name: 'tmk_def_3'
  frames: 'tmk_def_3-frames'
  split_file: 'def3TrainTestlist'
  split_number: 1

# train
train:
  num_epochs: 100
  batch_size: 8
  sequence_length: 10
  image_height: 224
  image_width: 224
  channels: 3
  latent_dim: 128
  lstm_layers: 3
  hidden_dim: 256
  bidirectional: True
  attention: True
  num_workers: 4
  checkpoint_model: ''
  checkpoint_interval: 10
  checkpoints_dir: 'checkpoints'
  tensorboard_dir: 'logs'
  resume: True

# test or test_on_video
test:
  num_classes: 6
  batch_size: 1
  sequence_length: 10
  image_height: 224
  image_width: 224
  channels: 3
  latent_dim: 128
  lstm_layers: 3
  hidden_dim: 256
  bidirectional: True
  attention: True
  num_workers: 4
  checkpoint_model: '/home/jakhremchik/Documents/code/TMK/Action-Recognition-CNN-LSTM/outputs/checkpoints/checkpoint_0090.pth'
  # video_name: 'seq1_empty.mp4'
  # video_name: '2.mp4'
  video_name: '3.mp4'
  # frames: 'tmk_def_3-frames/Empty/seq_1/'
